// Code generated by AI assistant — custom tool libraries & HTTP tools (first-class tool management).
package types

import (
	"database/sql/driver"
	"encoding/json"
	"log"
	"time"

	"github.com/Tencent/WeKnora/internal/utils"
	"github.com/google/uuid"
	"gorm.io/gorm"
)

// ToolLibrary is a group of tools (builtin or user-created). The builtin
// library is seeded per-tenant and aggregates builtin Go tools in the
// ListAllTools API; user libraries hold CustomTool rows.
type ToolLibrary struct {
	ID          string         `json:"id"          gorm:"type:varchar(36);primaryKey"`
	TenantID    uint64         `json:"tenant_id"   gorm:"not null;uniqueIndex:idx_tool_libraries_tenant_name"`
	Name        string         `json:"name"        gorm:"type:varchar(255);not null;uniqueIndex:idx_tool_libraries_tenant_name"`
	Description string         `json:"description" gorm:"type:text"`
	IsBuiltin   bool           `json:"is_builtin"  gorm:"not null;default:false"`
	SortOrder   int            `json:"sort_order"  gorm:"not null;default:0"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	DeletedAt   gorm.DeletedAt `json:"deleted_at"  gorm:"index"`
}

// BeforeCreate ensures a UUID is assigned.
func (l *ToolLibrary) BeforeCreate(tx *gorm.DB) error {
	if l.ID == "" {
		l.ID = uuid.New().String()
	}
	return nil
}

// HTTPToolAuthType enumerates authentication strategies for an HTTP tool.
type HTTPToolAuthType string

const (
	HTTPAuthNone   HTTPToolAuthType = ""       // no auth
	HTTPAuthBearer HTTPToolAuthType = "bearer" // Authorization: Bearer <token>
	HTTPAuthAPIKey HTTPToolAuthType = "apikey" // custom header carrying Token
	HTTPAuthBasic  HTTPToolAuthType = "basic"  // basic auth (Token = user:pass)
)

// HTTPToolAuth carries the secret used to authenticate outbound HTTP calls.
// Token is AES-encrypted at rest (Value/Scan below) and stripped from
// response DTOs.
type HTTPToolAuth struct {
	AuthType HTTPToolAuthType `json:"auth_type,omitempty"`
	Token    string           `json:"token,omitempty"`      // encrypted at rest
	Header   string           `json:"header,omitempty"`     // apikey header name; default X-API-Key
	Username string           `json:"username,omitempty"`   // basic auth username (basic)
}

// Value encrypts Token when SYSTEM_AES_KEY is configured.
func (a *HTTPToolAuth) Value() (driver.Value, error) {
	if a == nil {
		return nil, nil
	}
	out := *a
	if key := utils.GetAESKey(); key != nil && out.Token != "" {
		if encrypted, err := utils.EncryptAESGCM(out.Token, key); err == nil {
			out.Token = encrypted
		}
	}
	return json.Marshal(&out)
}

// Scan decrypts Token; legacy plaintext rows are returned as-is.
func (a *HTTPToolAuth) Scan(value interface{}) error {
	if value == nil {
		return nil
	}
	b, ok := value.([]byte)
	if !ok {
		return nil
	}
	if err := json.Unmarshal(b, a); err != nil {
		return err
	}
	if plain, ok := utils.DecryptStoredSecretLenient(a.Token); ok {
		a.Token = plain
	} else {
		log.Printf("[crypto] http_tool auth token: decrypt failed (SYSTEM_AES_KEY missing/rotated?), treating as unconfigured")
		a.Token = ""
	}
	return nil
}

// HTTPToolConfig describes how to invoke the remote HTTP endpoint.
type HTTPToolConfig struct {
	Method          string            `json:"method"`                     // GET/POST/PUT/PATCH/DELETE
	URLTemplate     string            `json:"url_template"`               // e.g. https://api.x.com/v1/{id}
	Headers         map[string]string `json:"headers,omitempty"`          // static headers (non-secret)
	BodyTemplate    string            `json:"body_template,omitempty"`    // JSON body template, {var} placeholders
	Auth            *HTTPToolAuth     `json:"auth,omitempty"`             // secret auth (encrypted)
	ResponseExtract string            `json:"response_extract,omitempty"` // optional JSONPath into response body
	TimeoutSec      int               `json:"timeout_sec,omitempty"`      // 0 => default 30s
}

// Value serializes the config; Auth handles its own encryption via its Value.
func (c *HTTPToolConfig) Value() (driver.Value, error) {
	if c == nil {
		return nil, nil
	}
	return json.Marshal(c)
}

// Scan deserializes the config (Auth.Scan decrypts the token).
func (c *HTTPToolConfig) Scan(value interface{}) error {
	if value == nil {
		return nil
	}
	b, ok := value.([]byte)
	if !ok {
		return nil
	}
	return json.Unmarshal(b, c)
}

// JSONSchema is a persisted JSON Schema (parameters_schema) wrapper.
type JSONSchema json.RawMessage

// Value serializes the schema.
func (s JSONSchema) Value() (driver.Value, error) {
	if len(s) == 0 {
		return nil, nil
	}
	return []byte(s), nil
}

// Scan deserializes the schema.
func (s *JSONSchema) Scan(value interface{}) error {
	if value == nil {
		*s = nil
		return nil
	}
	b, ok := value.([]byte)
	if !ok {
		return nil
	}
	cp := make(JSONSchema, len(b))
	copy(cp, b)
	*s = cp
	return nil
}

// MarshalJSON returns the raw JSON bytes.
func (s JSONSchema) MarshalJSON() ([]byte, error) {
	if len(s) == 0 {
		return []byte("null"), nil
	}
	return []byte(s), nil
}

// UnmarshalJSON copies the raw bytes.
func (s *JSONSchema) UnmarshalJSON(data []byte) error {
	if s == nil {
		return nil
	}
	cp := make(JSONSchema, len(data))
	copy(cp, data)
	*s = cp
	return nil
}

// CustomTool is a user-registered HTTP API tool. At agent runtime it is
// instantiated as an HTTPTool and registered into the ToolRegistry under
// its Name, indistinguishable from builtin tools to the LLM.
type CustomTool struct {
	ID              string         `json:"id"               gorm:"type:varchar(36);primaryKey"`
	TenantID        uint64         `json:"tenant_id"        gorm:"not null;uniqueIndex:idx_custom_tools_tenant_name"`
	LibraryID       string         `json:"library_id"       gorm:"type:varchar(36);not null;index:idx_custom_tools_tenant_lib"`
	Name            string         `json:"name"             gorm:"type:varchar(64);not null;uniqueIndex:idx_custom_tools_tenant_name"`
	DisplayName     string         `json:"display_name"     gorm:"type:varchar(128)"`
	Description     string         `json:"description"      gorm:"type:text;not null"`
	ParametersSchema JSONSchema    `json:"parameters_schema" gorm:"type:jsonb"`
	HTTPConfig      HTTPToolConfig `json:"http_config"      gorm:"type:jsonb;not null"`
	Enabled         bool           `json:"enabled"          gorm:"not null;default:true"`
	RequireApproval bool           `json:"require_approval" gorm:"not null;default:false"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	DeletedAt       gorm.DeletedAt `json:"deleted_at"       gorm:"index"`
}

// BeforeCreate ensures a UUID is assigned.
func (t *CustomTool) BeforeCreate(tx *gorm.DB) error {
	if t.ID == "" {
		t.ID = uuid.New().String()
	}
	return nil
}

// IsBuiltinName reports whether name collides with a builtin tool name.
// Callers (service layer) use this to reject creation of custom tools that
// would shadow builtin tools — the ToolRegistry is first-wins, so a custom
// tool with a builtin name would be silently dropped at runtime.
// The actual builtin name set is provided by tools.AvailableToolDefinitions.
func IsBuiltinToolName(name string, builtinNames map[string]struct{}) bool {
	_, ok := builtinNames[name]
	return ok
}
