// Code generated by AI assistant — tool library & custom tool service (first-class tool management).
package service

import (
	"context"
	"errors"
	"fmt"
	"regexp"
	"strings"
	"time"

	"github.com/Tencent/WeKnora/internal/agent/tools"
	"github.com/Tencent/WeKnora/internal/types"
	"github.com/Tencent/WeKnora/internal/types/interfaces"
	"github.com/Tencent/WeKnora/internal/utils"
	"github.com/google/uuid"
)

// customToolNamePattern restricts tool names fed to LLM function-calling:
// lowercase, alphanumeric + underscore, 3-63 chars, must start with a letter.
var customToolNamePattern = regexp.MustCompile(`^[a-z][a-z0-9_]{2,62}$`)

// builtinToolGroup maps a builtin tool name to its UI group. Mirrors the
// frontend AgentEditorModal grouping (base/rag/wiki_*/data) so the unified
// ListAllTools API can replace the hardcoded frontend list.
func builtinToolGroup(name string) string {
	switch {
	case name == "thinking", name == "todo_write":
		return "base"
	case strings.HasPrefix(name, "wiki_"):
		// keep wiki sub-groups aligned with frontend toolGroups
		switch name {
		case "wiki_write_page", "wiki_replace_text", "wiki_rename_page", "wiki_delete_page":
			return "wiki_edit"
		case "wiki_flag_issue", "wiki_read_issue", "wiki_update_issue":
			return "wiki_issue"
		default:
			return "wiki_read"
		}
	case strings.HasPrefix(name, "data_"):
		return "data"
	case name == "web_search", name == "web_fetch":
		return "web"
	case name == "read_skill", name == "execute_skill_script":
		return "skills"
	default:
		return "rag"
	}
}

// toolService implements interfaces.ToolService.
type toolService struct {
	libRepo  interfaces.ToolLibraryRepository
	toolRepo interfaces.CustomToolRepository
}

// NewToolService creates a new tool service.
func NewToolService(libRepo interfaces.ToolLibraryRepository, toolRepo interfaces.CustomToolRepository) interfaces.ToolService {
	return &toolService{libRepo: libRepo, toolRepo: toolRepo}
}

// ---- Library CRUD ----

func (s *toolService) CreateToolLibrary(ctx context.Context, tenantID uint64, name, description string) (*types.ToolLibrary, error) {
	if strings.TrimSpace(name) == "" {
		return nil, errors.New("library name is required")
	}
	lib := &types.ToolLibrary{
		ID:          uuid.New().String(),
		TenantID:    tenantID,
		Name:        strings.TrimSpace(name),
		Description: description,
	}
	if err := s.libRepo.Create(ctx, lib); err != nil {
		return nil, fmt.Errorf("create tool library: %w", err)
	}
	return lib, nil
}

func (s *toolService) ListToolLibraries(ctx context.Context, tenantID uint64) ([]*types.ToolLibrary, error) {
	if _, err := s.libRepo.EnsureBuiltin(ctx, tenantID); err != nil {
		return nil, fmt.Errorf("ensure builtin library: %w", err)
	}
	return s.libRepo.List(ctx, tenantID)
}

func (s *toolService) UpdateToolLibrary(ctx context.Context, tenantID uint64, id, name, description string) error {
	if strings.TrimSpace(name) == "" {
		return errors.New("library name is required")
	}
	lib := &types.ToolLibrary{
		ID:          id,
		TenantID:    tenantID,
		Name:        strings.TrimSpace(name),
		Description: description,
		UpdatedAt:   time.Now(),
	}
	if err := s.libRepo.Update(ctx, lib); err != nil {
		return fmt.Errorf("update tool library: %w", err)
	}
	return nil
}

func (s *toolService) DeleteToolLibrary(ctx context.Context, tenantID uint64, id string) error {
	// Reject deleting the builtin library explicitly (repo also guards, but
	// surface a clear error here).
	lib, err := s.libRepo.GetByID(ctx, tenantID, id)
	if err != nil {
		return fmt.Errorf("get tool library: %w", err)
	}
	if lib == nil {
		return errors.New("tool library not found")
	}
	if lib.IsBuiltin {
		return errors.New("builtin tool library cannot be deleted")
	}
	if err := s.libRepo.Delete(ctx, tenantID, id); err != nil {
		return fmt.Errorf("delete tool library: %w", err)
	}
	return nil
}

// ---- Custom tool CRUD ----

func (s *toolService) CreateCustomTool(ctx context.Context, tenantID uint64, tool *types.CustomTool) (*types.CustomTool, error) {
	if err := s.validateCustomTool(ctx, tenantID, tool, true); err != nil {
		return nil, err
	}
	// Ensure the chosen library exists and belongs to this tenant (and is not
	// the builtin library — builtin tools are code-defined, not user-created).
	lib, err := s.libRepo.GetByID(ctx, tenantID, tool.LibraryID)
	if err != nil {
		return nil, fmt.Errorf("get tool library: %w", err)
	}
	if lib == nil {
		return nil, errors.New("tool library not found")
	}
	if lib.IsBuiltin {
		return nil, errors.New("cannot add custom tools to the builtin library")
	}
	tool.ID = uuid.New().String()
	tool.TenantID = tenantID
	if err := s.toolRepo.Create(ctx, tool); err != nil {
		return nil, fmt.Errorf("create custom tool: %w", err)
	}
	return tool, nil
}

func (s *toolService) GetCustomTool(ctx context.Context, tenantID uint64, id string) (*types.CustomTool, error) {
	return s.toolRepo.GetByID(ctx, tenantID, id)
}

func (s *toolService) ListCustomToolsByLibrary(ctx context.Context, tenantID uint64, libraryID string) ([]*types.CustomTool, error) {
	return s.toolRepo.ListByLibrary(ctx, tenantID, libraryID)
}

func (s *toolService) UpdateCustomTool(ctx context.Context, tenantID uint64, id string, tool *types.CustomTool) error {
	existing, err := s.toolRepo.GetByID(ctx, tenantID, id)
	if err != nil {
		return fmt.Errorf("get custom tool: %w", err)
	}
	if existing == nil {
		return errors.New("custom tool not found")
	}
	// name is immutable; keep the existing name to preserve allowed_tools refs.
	tool.ID = id
	tool.TenantID = tenantID
	tool.Name = existing.Name
	tool.UpdatedAt = time.Now()
	if err := s.validateCustomTool(ctx, tenantID, tool, false); err != nil {
		return err
	}
	if err := s.toolRepo.Update(ctx, tool); err != nil {
		return fmt.Errorf("update custom tool: %w", err)
	}
	return nil
}

func (s *toolService) DeleteCustomTool(ctx context.Context, tenantID uint64, id string) error {
	if err := s.toolRepo.Delete(ctx, tenantID, id); err != nil {
		return fmt.Errorf("delete custom tool: %w", err)
	}
	return nil
}

// validateCustomTool checks name format + builtin-name collision + http_config.
// When isCreate is true, name uniqueness is also enforced.
func (s *toolService) validateCustomTool(ctx context.Context, tenantID uint64, tool *types.CustomTool, isCreate bool) error {
	name := strings.TrimSpace(tool.Name)
	if !customToolNamePattern.MatchString(name) {
		return fmt.Errorf("tool name must match %s (3-63 chars, lowercase, start with letter)", customToolNamePattern.String())
	}
	tool.Name = name
	if strings.TrimSpace(tool.Description) == "" {
		return errors.New("tool description is required")
	}
	if tool.HTTPConfig.URLTemplate == "" {
		return errors.New("http_config.url_template is required")
	}
	if tool.HTTPConfig.Method == "" {
		tool.HTTPConfig.Method = "GET"
	}
	tool.HTTPConfig.Method = strings.ToUpper(tool.HTTPConfig.Method)
	switch tool.HTTPConfig.Method {
	case "GET", "POST", "PUT", "PATCH", "DELETE":
	default:
		return fmt.Errorf("unsupported http method: %s", tool.HTTPConfig.Method)
	}
	if tool.HTTPConfig.TimeoutSec <= 0 {
		tool.HTTPConfig.TimeoutSec = 30
	}
	// Reject names that shadow builtin tools (registry is first-wins, so a
	// custom tool with a builtin name would be silently dropped at runtime).
	for _, b := range tools.AvailableToolDefinitions() {
		if b.Name == name {
			return fmt.Errorf("tool name %q conflicts with a builtin tool", name)
		}
	}
	if isCreate {
		if existing, err := s.toolRepo.GetByName(ctx, tenantID, name); err != nil {
			return fmt.Errorf("check tool name uniqueness: %w", err)
		} else if existing != nil {
			return fmt.Errorf("tool name %q already exists in this tenant", name)
		}
	}
	return nil
}

// ---- Test / runtime helpers ----

func (s *toolService) TestCustomTool(ctx context.Context, tenantID uint64, id string, args types.JSONSchema) (*types.ToolResult, error) {
	tool, err := s.toolRepo.GetByID(ctx, tenantID, id)
	if err != nil {
		return nil, fmt.Errorf("get custom tool: %w", err)
	}
	if tool == nil {
		return nil, errors.New("custom tool not found")
	}
	ht := tools.NewHTTPTool(tool)
	res, err := ht.Execute(ctx, []byte(args))
	if err != nil {
		return &types.ToolResult{Success: false, Error: err.Error()}, nil
	}
	return res, nil
}

func (s *toolService) ListEnabledCustomTools(ctx context.Context, tenantID uint64) ([]*types.CustomTool, error) {
	return s.toolRepo.ListEnabled(ctx, tenantID)
}

func (s *toolService) ListCustomToolsByNames(ctx context.Context, tenantID uint64, names []string) ([]*types.CustomTool, error) {
	return s.toolRepo.ListByNames(ctx, tenantID, names)
}

// ---- Aggregation ----

// ListAllTools merges builtin tool definitions (from tools.AvailableToolDefinitions)
// with user-created custom tools (from DB), grouped by library. The builtin
// library is virtual: its row is seeded lazily via EnsureBuiltin and its tool
// list is injected here from code, not persisted.
func (s *toolService) ListAllTools(ctx context.Context, tenantID uint64) ([]*interfaces.ToolLibraryWithTools, error) {
	builtinID, err := s.libRepo.EnsureBuiltin(ctx, tenantID)
	if err != nil {
		return nil, fmt.Errorf("ensure builtin library: %w", err)
	}
	libs, err := s.libRepo.List(ctx, tenantID)
	if err != nil {
		return nil, fmt.Errorf("list tool libraries: %w", err)
	}
	// Pre-load custom tools for all user libraries in one query per lib.
	// (Libraries count is small; a single ListEnabled + bucket would also work.)
	byLib := make(map[string][]*types.CustomTool, len(libs))
	for _, lib := range libs {
		if lib.IsBuiltin {
			continue
		}
		ts, err := s.toolRepo.ListByLibrary(ctx, tenantID, lib.ID)
		if err != nil {
			return nil, fmt.Errorf("list custom tools for library %s: %w", lib.ID, err)
		}
		byLib[lib.ID] = ts
	}

	out := make([]*interfaces.ToolLibraryWithTools, 0, len(libs))
	for _, lib := range libs {
		entry := &interfaces.ToolLibraryWithTools{
			ID:          lib.ID,
			Name:        lib.Name,
			Description: lib.Description,
			IsBuiltin:   lib.IsBuiltin,
			SortOrder:   lib.SortOrder,
			Tools:       []interfaces.ToolDefinition{},
		}
		if lib.IsBuiltin {
			entry.ID = builtinID
			for _, b := range tools.AvailableToolDefinitions() {
				entry.Tools = append(entry.Tools, interfaces.ToolDefinition{
					Name:        b.Name,
					DisplayName: b.Label,
					Description: b.Description,
					Group:       builtinToolGroup(b.Name),
				})
			}
		} else {
			for _, t := range byLib[lib.ID] {
				entry.Tools = append(entry.Tools, interfaces.ToolDefinition{
					Name:        t.Name,
					DisplayName: t.DisplayName,
					Description: t.Description,
					Group:       "http",
					Parameters:  t.ParametersSchema,
					Danger:      t.RequireApproval,
				})
			}
		}
		out = append(out, entry)
	}
	return out, nil
}

// SSRFPrecheck validates an http_config URL template before persistence.
// ponytail: the actual URL is only known after template rendering at call
// time, so we validate the literal host segment of the template here as a
// first line of defense; HTTPTool.Execute re-validates the rendered URL.
var _ = utils.ValidateURLForSSRF
