// Code generated by AI assistant — tool library & custom tool API client.
import { get, post, put, del } from "../../utils/request";

// 统一工具定义（内置 + 自定义共用）
export interface ToolDefinition {
  name: string;
  display_name: string;
  description: string;
  group: string; // base/rag/wiki_read/wiki_edit/wiki_issue/data/web/skills/http
  parameters?: Record<string, any>;
  danger: boolean;
}

// 工具库（含其下工具）— ListAllTools 返回结构
export interface ToolLibraryWithTools {
  id: string;
  name: string;
  description: string;
  is_builtin: boolean;
  sort_order: number;
  tools: ToolDefinition[];
}

// 工具库（不含工具，库 CRUD 用）
export interface ToolLibrary {
  id: string;
  tenant_id: number;
  name: string;
  description: string;
  is_builtin: boolean;
  sort_order: number;
  created_at: string;
  updated_at: string;
}

// HTTP 工具鉴权（响应不含 token，只有 configured 标志）
export interface HTTPToolAuth {
  auth_type?: string;
  header?: string;
  username?: string;
  configured: boolean;
}

export interface HTTPToolConfig {
  method: string;
  url_template: string;
  headers?: Record<string, string>;
  body_template?: string;
  auth?: HTTPToolAuth;
  response_extract?: string;
  timeout_sec?: number;
}

// 自定义工具（响应 DTO）
export interface CustomTool {
  id: string;
  tenant_id: number;
  library_id: string;
  name: string;
  display_name: string;
  description: string;
  parameters_schema?: Record<string, any>;
  http_config: HTTPToolConfig;
  enabled: boolean;
  require_approval: boolean;
  created_at: string;
  updated_at: string;
}

// 创建/更新自定义工具的请求体（auth.token 为明文，由后端加密）
export interface CustomToolRequest {
  name: string;
  display_name?: string;
  description: string;
  parameters_schema?: Record<string, any>;
  http_config: {
    method: string;
    url_template: string;
    headers?: Record<string, string>;
    body_template?: string;
    auth?: { auth_type?: string; token?: string; header?: string; username?: string };
    response_extract?: string;
    timeout_sec?: number;
  };
  enabled?: boolean;
  require_approval?: boolean;
}

// 工具执行结果
export interface ToolResult {
  success: boolean;
  output: string;
  error?: string;
  data?: Record<string, any>;
  images?: string[];
}

// 聚合：获取所有工具（按库分组），agent 编辑器用
export function listAllTools() {
  return get<{ data: ToolLibraryWithTools[] }>('/api/v1/tools');
}

// 工具库 CRUD
export function listToolLibraries() {
  return get<{ data: ToolLibrary[] }>('/api/v1/tool-libraries');
}

export function createToolLibrary(name: string, description: string) {
  return post<{ data: ToolLibrary }>('/api/v1/tool-libraries', { name, description });
}

export function updateToolLibrary(id: string, name: string, description: string) {
  return put<{ data: null }>(`/api/v1/tool-libraries/${id}`, { name, description });
}

export function deleteToolLibrary(id: string) {
  return del<{ data: null }>(`/api/v1/tool-libraries/${id}`);
}

// 自定义工具 CRUD
export function createCustomTool(libraryId: string, tool: CustomToolRequest) {
  return post<{ data: CustomTool }>(`/api/v1/tool-libraries/${libraryId}/tools`, tool);
}

export function listCustomToolsByLibrary(libraryId: string) {
  return get<{ data: CustomTool[] }>(`/api/v1/tool-libraries/${libraryId}/tools`);
}

export function updateCustomTool(id: string, tool: CustomToolRequest) {
  return put<{ data: null }>(`/api/v1/tools/${id}`, tool);
}

export function deleteCustomTool(id: string) {
  return del<{ data: null }>(`/api/v1/tools/${id}`);
}

// 测试自定义工具调用
export function testCustomTool(id: string, args: Record<string, any>) {
  return post<{ data: ToolResult }>(`/api/v1/tools/${id}/test`, { args });
}
