// Code generated by AI assistant — tool library & custom tool HTTP handlers.
package handler

import (
	"encoding/json"
	"net/http"

	"github.com/Tencent/WeKnora/internal/errors"
	"github.com/Tencent/WeKnora/internal/handler/dto"
	"github.com/Tencent/WeKnora/internal/logger"
	"github.com/Tencent/WeKnora/internal/types"
	"github.com/Tencent/WeKnora/internal/types/interfaces"
	"github.com/gin-gonic/gin"
)

// ToolHandler handles tool library and custom tool HTTP requests.
type ToolHandler struct {
	toolService interfaces.ToolService
}

// NewToolHandler creates a new tool handler.
func NewToolHandler(toolService interfaces.ToolService) *ToolHandler {
	return &ToolHandler{toolService: toolService}
}

func tenantIDFrom(c *gin.Context) (uint64, bool) {
	tid := c.GetUint64(types.TenantIDContextKey.String())
	if tid == 0 {
		c.Error(errors.NewBadRequestError("Tenant ID cannot be empty"))
		return 0, false
	}
	return tid, true
}

// ---- Aggregation ----

// ListAllTools godoc
// @Summary   获取所有工具（按库分组）
// @Tags      工具
// @Success   200  {object}  map[string]interface{}
// @Router    /tools [get]
func (h *ToolHandler) ListAllTools(c *gin.Context) {
	ctx := c.Request.Context()
	tid, ok := tenantIDFrom(c)
	if !ok {
		return
	}
	libs, err := h.toolService.ListAllTools(ctx, tid)
	if err != nil {
		logger.ErrorWithFields(ctx, err, map[string]interface{}{"tenant_id": tid})
		c.Error(errors.NewInternalServerError("Failed to list tools: " + err.Error()))
		return
	}
	c.JSON(http.StatusOK, gin.H{"success": true, "data": libs})
}

// ---- Library CRUD ----

// CreateToolLibrary godoc
// @Summary   创建工具库
// @Tags      工具库
// @Param     request body createLibraryRequest true "工具库配置"
// @Router    /tool-libraries [post]
func (h *ToolHandler) CreateToolLibrary(c *gin.Context) {
	ctx := c.Request.Context()
	tid, ok := tenantIDFrom(c)
	if !ok {
		return
	}
	var req createToolLibraryRequest
	if err := c.ShouldBindJSON(&req); err != nil {
		c.Error(errors.NewBadRequestError(err.Error()))
		return
	}
	lib, err := h.toolService.CreateToolLibrary(ctx, tid, req.Name, req.Description)
	if err != nil {
		c.Error(errors.NewBadRequestError(err.Error()))
		return
	}
	c.JSON(http.StatusOK, gin.H{"success": true, "data": dto.NewToolLibraryResponse(lib)})
}

// ListToolLibraries godoc
// @Summary   获取工具库列表
// @Tags      工具库
// @Router    /tool-libraries [get]
func (h *ToolHandler) ListToolLibraries(c *gin.Context) {
	ctx := c.Request.Context()
	tid, ok := tenantIDFrom(c)
	if !ok {
		return
	}
	libs, err := h.toolService.ListToolLibraries(ctx, tid)
	if err != nil {
		c.Error(errors.NewInternalServerError("Failed to list tool libraries: " + err.Error()))
		return
	}
	c.JSON(http.StatusOK, gin.H{"success": true, "data": dto.NewToolLibraryResponses(libs)})
}

// UpdateToolLibrary godoc
// @Summary   更新工具库
// @Param     request body createLibraryRequest true "工具库配置"
// @Router    /tool-libraries/{id} [put]
func (h *ToolHandler) UpdateToolLibrary(c *gin.Context) {
	ctx := c.Request.Context()
	tid, ok := tenantIDFrom(c)
	if !ok {
		return
	}
	id := c.Param("id")
	var req createToolLibraryRequest
	if err := c.ShouldBindJSON(&req); err != nil {
		c.Error(errors.NewBadRequestError(err.Error()))
		return
	}
	if err := h.toolService.UpdateToolLibrary(ctx, tid, id, req.Name, req.Description); err != nil {
		c.Error(errors.NewBadRequestError(err.Error()))
		return
	}
	c.JSON(http.StatusOK, gin.H{"success": true})
}

// DeleteToolLibrary godoc
// @Summary   删除工具库
// @Router    /tool-libraries/{id} [delete]
func (h *ToolHandler) DeleteToolLibrary(c *gin.Context) {
	ctx := c.Request.Context()
	tid, ok := tenantIDFrom(c)
	if !ok {
		return
	}
	id := c.Param("id")
	if err := h.toolService.DeleteToolLibrary(ctx, tid, id); err != nil {
		c.Error(errors.NewBadRequestError(err.Error()))
		return
	}
	c.JSON(http.StatusOK, gin.H{"success": true})
}

// ---- Custom tool CRUD ----

// CreateCustomTool godoc
// @Summary   在指定工具库下创建自定义工具
// @Param     request body types.CustomTool true "工具配置"
// @Router    /tool-libraries/{libId}/tools [post]
func (h *ToolHandler) CreateCustomTool(c *gin.Context) {
	ctx := c.Request.Context()
	tid, ok := tenantIDFrom(c)
	if !ok {
		return
	}
	libID := c.Param("libId")
	var tool types.CustomTool
	if err := c.ShouldBindJSON(&tool); err != nil {
		c.Error(errors.NewBadRequestError(err.Error()))
		return
	}
	tool.LibraryID = libID
	created, err := h.toolService.CreateCustomTool(ctx, tid, &tool)
	if err != nil {
		c.Error(errors.NewBadRequestError(err.Error()))
		return
	}
	c.JSON(http.StatusOK, gin.H{"success": true, "data": dto.NewCustomToolResponse(created)})
}

// ListCustomToolsByLibrary godoc
// @Summary   获取工具库下的工具列表
// @Router    /tool-libraries/{libId}/tools [get]
func (h *ToolHandler) ListCustomToolsByLibrary(c *gin.Context) {
	ctx := c.Request.Context()
	tid, ok := tenantIDFrom(c)
	if !ok {
		return
	}
	libID := c.Param("libId")
	tools, err := h.toolService.ListCustomToolsByLibrary(ctx, tid, libID)
	if err != nil {
		c.Error(errors.NewInternalServerError("Failed to list custom tools: " + err.Error()))
		return
	}
	c.JSON(http.StatusOK, gin.H{"success": true, "data": dto.NewCustomToolResponses(tools)})
}

// UpdateCustomTool godoc
// @Summary   更新自定义工具
// @Param     request body types.CustomTool true "工具配置"
// @Router    /tools/{id} [put]
func (h *ToolHandler) UpdateCustomTool(c *gin.Context) {
	ctx := c.Request.Context()
	tid, ok := tenantIDFrom(c)
	if !ok {
		return
	}
	id := c.Param("id")
	var tool types.CustomTool
	if err := c.ShouldBindJSON(&tool); err != nil {
		c.Error(errors.NewBadRequestError(err.Error()))
		return
	}
	if err := h.toolService.UpdateCustomTool(ctx, tid, id, &tool); err != nil {
		c.Error(errors.NewBadRequestError(err.Error()))
		return
	}
	c.JSON(http.StatusOK, gin.H{"success": true})
}

// DeleteCustomTool godoc
// @Summary   删除自定义工具
// @Router    /tools/{id} [delete]
func (h *ToolHandler) DeleteCustomTool(c *gin.Context) {
	ctx := c.Request.Context()
	tid, ok := tenantIDFrom(c)
	if !ok {
		return
	}
	id := c.Param("id")
	if err := h.toolService.DeleteCustomTool(ctx, tid, id); err != nil {
		c.Error(errors.NewInternalServerError("Failed to delete custom tool: " + err.Error()))
		return
	}
	c.JSON(http.StatusOK, gin.H{"success": true})
}

// TestCustomTool godoc
// @Summary   测试自定义工具调用
// @Param     request body testToolRequest true "测试入参"
// @Router    /tools/{id}/test [post]
func (h *ToolHandler) TestCustomTool(c *gin.Context) {
	ctx := c.Request.Context()
	tid, ok := tenantIDFrom(c)
	if !ok {
		return
	}
	id := c.Param("id")
	var req testToolRequest
	if err := c.ShouldBindJSON(&req); err != nil {
		c.Error(errors.NewBadRequestError(err.Error()))
		return
	}
	res, err := h.toolService.TestCustomTool(ctx, tid, id, types.JSONSchema(req.Args))
	if err != nil {
		c.Error(errors.NewInternalServerError("Failed to test custom tool: " + err.Error()))
		return
	}
	c.JSON(http.StatusOK, gin.H{"success": true, "data": res})
}

// ---- request types ----

type createToolLibraryRequest struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

type testToolRequest struct {
	Args json.RawMessage `json:"args"`
}
