// Code generated by AI assistant — tool library & custom tool response DTOs.
package dto

import (
	"time"

	"github.com/Tencent/WeKnora/internal/types"
)

// HTTPToolAuthResponse mirrors types.HTTPToolAuth without the secret Token.
// AuthType/Header/Username are non-secret structural config; the Token
// presence is signalled via Configured so the UI can render a badge.
type HTTPToolAuthResponse struct {
	AuthType   types.HTTPToolAuthType `json:"auth_type,omitempty"`
	Header     string                 `json:"header,omitempty"`
	Username   string                 `json:"username,omitempty"`
	Configured bool                   `json:"configured"`
}

// HTTPToolConfigResponse mirrors types.HTTPToolConfig with auth redacted.
type HTTPToolConfigResponse struct {
	Method          string                `json:"method"`
	URLTemplate     string                `json:"url_template"`
	Headers         map[string]string     `json:"headers,omitempty"`
	BodyTemplate    string                `json:"body_template,omitempty"`
	Auth            *HTTPToolAuthResponse `json:"auth,omitempty"`
	ResponseExtract string                `json:"response_extract,omitempty"`
	TimeoutSec      int                   `json:"timeout_sec,omitempty"`
}

// CustomToolResponse is the response shape for a custom tool. Auth tokens are
// stripped; credential presence is exposed via Auth.Configured.
type CustomToolResponse struct {
	ID               string                 `json:"id"`
	TenantID         uint64                 `json:"tenant_id"`
	LibraryID        string                 `json:"library_id"`
	Name             string                 `json:"name"`
	DisplayName      string                 `json:"display_name"`
	Description      string                 `json:"description"`
	ParametersSchema types.JSONSchema       `json:"parameters_schema,omitempty"`
	HTTPConfig       HTTPToolConfigResponse `json:"http_config"`
	Enabled          bool                   `json:"enabled"`
	RequireApproval  bool                   `json:"require_approval"`
	CreatedAt        time.Time              `json:"created_at"`
	UpdatedAt        time.Time              `json:"updated_at"`
}

// NewCustomToolResponse converts a stored CustomTool into its response shape.
func NewCustomToolResponse(t *types.CustomTool) *CustomToolResponse {
	if t == nil {
		return nil
	}
	resp := &CustomToolResponse{
		ID:               t.ID,
		TenantID:         t.TenantID,
		LibraryID:        t.LibraryID,
		Name:             t.Name,
		DisplayName:      t.DisplayName,
		Description:      t.Description,
		ParametersSchema: t.ParametersSchema,
		HTTPConfig: HTTPToolConfigResponse{
			Method:          t.HTTPConfig.Method,
			URLTemplate:     t.HTTPConfig.URLTemplate,
			Headers:         t.HTTPConfig.Headers,
			BodyTemplate:    t.HTTPConfig.BodyTemplate,
			ResponseExtract: t.HTTPConfig.ResponseExtract,
			TimeoutSec:      t.HTTPConfig.TimeoutSec,
		},
		Enabled:         t.Enabled,
		RequireApproval: t.RequireApproval,
		CreatedAt:       t.CreatedAt,
		UpdatedAt:       t.UpdatedAt,
	}
	if t.HTTPConfig.Auth != nil {
		resp.HTTPConfig.Auth = &HTTPToolAuthResponse{
			AuthType:   t.HTTPConfig.Auth.AuthType,
			Header:     t.HTTPConfig.Auth.Header,
			Username:   t.HTTPConfig.Auth.Username,
			Configured: t.HTTPConfig.Auth.Token != "",
		}
	}
	return resp
}

// NewCustomToolResponses is the slice convenience wrapper.
func NewCustomToolResponses(ts []*types.CustomTool) []*CustomToolResponse {
	out := make([]*CustomToolResponse, 0, len(ts))
	for _, t := range ts {
		out = append(out, NewCustomToolResponse(t))
	}
	return out
}

// ToolLibraryResponse mirrors types.ToolLibrary for responses.
type ToolLibraryResponse struct {
	ID          string    `json:"id"`
	TenantID    uint64    `json:"tenant_id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	IsBuiltin   bool      `json:"is_builtin"`
	SortOrder   int       `json:"sort_order"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

// NewToolLibraryResponse converts a stored ToolLibrary into its response shape.
func NewToolLibraryResponse(l *types.ToolLibrary) *ToolLibraryResponse {
	if l == nil {
		return nil
	}
	return &ToolLibraryResponse{
		ID:          l.ID,
		TenantID:    l.TenantID,
		Name:        l.Name,
		Description: l.Description,
		IsBuiltin:   l.IsBuiltin,
		SortOrder:   l.SortOrder,
		CreatedAt:   l.CreatedAt,
		UpdatedAt:   l.UpdatedAt,
	}
}

// NewToolLibraryResponses is the slice convenience wrapper.
func NewToolLibraryResponses(ls []*types.ToolLibrary) []*ToolLibraryResponse {
	out := make([]*ToolLibraryResponse, 0, len(ls))
	for _, l := range ls {
		out = append(out, NewToolLibraryResponse(l))
	}
	return out
}
