// Code generated by AI assistant — tool library & custom tool repositories.
package repository

import (
	"context"
	"errors"

	"github.com/Tencent/WeKnora/internal/types"
	"github.com/Tencent/WeKnora/internal/types/interfaces"
	"github.com/google/uuid"
	"gorm.io/gorm"
)

// toolLibraryRepository implements interfaces.ToolLibraryRepository.
type toolLibraryRepository struct {
	db *gorm.DB
}

// NewToolLibraryRepository creates a new tool library repository.
func NewToolLibraryRepository(db *gorm.DB) interfaces.ToolLibraryRepository {
	return &toolLibraryRepository{db: db}
}

func (r *toolLibraryRepository) Create(ctx context.Context, lib *types.ToolLibrary) error {
	return r.db.WithContext(ctx).Create(lib).Error
}

func (r *toolLibraryRepository) GetByID(ctx context.Context, tenantID uint64, id string) (*types.ToolLibrary, error) {
	var lib types.ToolLibrary
	err := r.db.WithContext(ctx).
		Where("id = ? AND tenant_id = ?", id, tenantID).
		First(&lib).Error
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, nil
		}
		return nil, err
	}
	return &lib, nil
}

func (r *toolLibraryRepository) List(ctx context.Context, tenantID uint64) ([]*types.ToolLibrary, error) {
	var libs []*types.ToolLibrary
	err := r.db.WithContext(ctx).
		Where("tenant_id = ?", tenantID).
		Order("is_builtin DESC, sort_order ASC, created_at ASC").
		Find(&libs).Error
	if err != nil {
		return nil, err
	}
	return libs, nil
}

func (r *toolLibraryRepository) Update(ctx context.Context, lib *types.ToolLibrary) error {
	updateMap := map[string]interface{}{
		"updated_at":  lib.UpdatedAt,
		"name":        lib.Name,
		"description": lib.Description,
		"sort_order":  lib.SortOrder,
	}
	return r.db.WithContext(ctx).
		Model(&types.ToolLibrary{}).
		Where("id = ? AND tenant_id = ? AND is_builtin = false", lib.ID, lib.TenantID).
		Updates(updateMap).Error
}

func (r *toolLibraryRepository) Delete(ctx context.Context, tenantID uint64, id string) error {
	// Builtin library is protected: the WHERE clause refuses to touch it.
	return r.db.WithContext(ctx).
		Where("id = ? AND tenant_id = ? AND is_builtin = false", id, tenantID).
		Delete(&types.ToolLibrary{}).Error
}

// EnsureBuiltin lazily seeds the per-tenant builtin library row.
func (r *toolLibraryRepository) EnsureBuiltin(ctx context.Context, tenantID uint64) (string, error) {
	var lib types.ToolLibrary
	err := r.db.WithContext(ctx).
		Where("tenant_id = ? AND is_builtin = true", tenantID).
		First(&lib).Error
	if err == nil {
		return lib.ID, nil
	}
	if !errors.Is(err, gorm.ErrRecordNotFound) {
		return "", err
	}
	lib = types.ToolLibrary{
		ID:          uuid.New().String(),
		TenantID:    tenantID,
		Name:        "builtin",
		Description: "Built-in tools",
		IsBuiltin:   true,
		SortOrder:   -1,
	}
	if err := r.db.WithContext(ctx).Create(&lib).Error; err != nil {
		return "", err
	}
	return lib.ID, nil
}

// customToolRepository implements interfaces.CustomToolRepository.
type customToolRepository struct {
	db *gorm.DB
}

// NewCustomToolRepository creates a new custom tool repository.
func NewCustomToolRepository(db *gorm.DB) interfaces.CustomToolRepository {
	return &customToolRepository{db: db}
}

func (r *customToolRepository) Create(ctx context.Context, tool *types.CustomTool) error {
	return r.db.WithContext(ctx).Create(tool).Error
}

func (r *customToolRepository) GetByID(ctx context.Context, tenantID uint64, id string) (*types.CustomTool, error) {
	var tool types.CustomTool
	err := r.db.WithContext(ctx).
		Where("id = ? AND tenant_id = ?", id, tenantID).
		First(&tool).Error
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, nil
		}
		return nil, err
	}
	return &tool, nil
}

func (r *customToolRepository) GetByName(ctx context.Context, tenantID uint64, name string) (*types.CustomTool, error) {
	var tool types.CustomTool
	err := r.db.WithContext(ctx).
		Where("tenant_id = ? AND name = ?", tenantID, name).
		First(&tool).Error
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, nil
		}
		return nil, err
	}
	return &tool, nil
}

func (r *customToolRepository) ListByLibrary(ctx context.Context, tenantID uint64, libraryID string) ([]*types.CustomTool, error) {
	var tools []*types.CustomTool
	err := r.db.WithContext(ctx).
		Where("tenant_id = ? AND library_id = ?", tenantID, libraryID).
		Order("created_at ASC").
		Find(&tools).Error
	if err != nil {
		return nil, err
	}
	return tools, nil
}

func (r *customToolRepository) ListEnabled(ctx context.Context, tenantID uint64) ([]*types.CustomTool, error) {
	var tools []*types.CustomTool
	err := r.db.WithContext(ctx).
		Where("tenant_id = ? AND enabled = ?", tenantID, true).
		Order("created_at ASC").
		Find(&tools).Error
	if err != nil {
		return nil, err
	}
	return tools, nil
}

func (r *customToolRepository) ListByNames(ctx context.Context, tenantID uint64, names []string) ([]*types.CustomTool, error) {
	if len(names) == 0 {
		return []*types.CustomTool{}, nil
	}
	var tools []*types.CustomTool
	err := r.db.WithContext(ctx).
		Where("tenant_id = ? AND enabled = ? AND name IN ?", tenantID, true, names).
		Find(&tools).Error
	if err != nil {
		return nil, err
	}
	return tools, nil
}

func (r *customToolRepository) Update(ctx context.Context, tool *types.CustomTool) error {
	updateMap := map[string]interface{}{
		"updated_at":        tool.UpdatedAt,
		"display_name":      tool.DisplayName,
		"description":       tool.Description,
		"parameters_schema": tool.ParametersSchema,
		"http_config":       tool.HTTPConfig,
		"enabled":           tool.Enabled,
		"require_approval":  tool.RequireApproval,
	}
	if tool.LibraryID != "" {
		updateMap["library_id"] = tool.LibraryID
	}
	// name is immutable post-create to keep allowed_tools references stable.
	return r.db.WithContext(ctx).
		Model(&types.CustomTool{}).
		Where("id = ? AND tenant_id = ?", tool.ID, tool.TenantID).
		Updates(updateMap).Error
}

func (r *customToolRepository) Delete(ctx context.Context, tenantID uint64, id string) error {
	return r.db.WithContext(ctx).
		Where("id = ? AND tenant_id = ?", id, tenantID).
		Delete(&types.CustomTool{}).Error
}
