// Code generated by AI assistant — HTTPTool wraps a user-registered HTTP API
// endpoint as a builtin-equivalent agent tool. It implements types.Tool and is
// registered into the ToolRegistry alongside builtin tools, so the LLM treats
// it identically. SSRF protection reuses the same utils used by web_fetch.
package tools

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/Tencent/WeKnora/internal/types"
	"github.com/Tencent/WeKnora/internal/utils"
)

// maxHTTPToolOutputBytes caps the raw response returned to the LLM to avoid
// blowing the context window with a runaway API response.
const maxHTTPToolOutputBytes = 64 * 1024

// HTTPTool implements types.Tool for a user-registered HTTP API endpoint.
type HTTPTool struct {
	name        string
	description string
	schema      json.RawMessage
	cfg         types.HTTPToolConfig
	client      *http.Client
}

// NewHTTPTool builds an HTTPTool from a persisted CustomTool definition.
func NewHTTPTool(tool *types.CustomTool) *HTTPTool {
	schema := json.RawMessage(tool.ParametersSchema)
	if len(schema) == 0 {
		schema = json.RawMessage(`{"type":"object","properties":{}}`)
	}
	timeout := time.Duration(tool.HTTPConfig.TimeoutSec) * time.Second
	if timeout <= 0 {
		timeout = 30 * time.Second
	}
	ssrfCfg := utils.DefaultSSRFSafeHTTPClientConfig()
	ssrfCfg.Timeout = timeout
	return &HTTPTool{
		name:        tool.Name,
		description: tool.Description,
		schema:      schema,
		cfg:         tool.HTTPConfig,
		client:      utils.NewSSRFSafeHTTPClient(ssrfCfg),
	}
}

// Name returns the tool name.
func (t *HTTPTool) Name() string { return t.name }

// Description returns the tool description.
func (t *HTTPTool) Description() string { return t.description }

// Parameters returns the JSON Schema for the tool's parameters.
func (t *HTTPTool) Parameters() json.RawMessage { return t.schema }

// Execute renders the URL/body templates with args, performs the HTTP call
// (SSRF-validated), and wraps the response as a ToolResult.
func (t *HTTPTool) Execute(ctx context.Context, args json.RawMessage) (*types.ToolResult, error) {
	var params map[string]interface{}
	if len(args) > 0 {
		if err := json.Unmarshal(args, &params); err != nil {
			return &types.ToolResult{Success: false, Error: fmt.Sprintf("invalid args JSON: %v", err)}, nil
		}
	}

	renderedURL, err := renderURLTemplate(t.cfg.URLTemplate, params)
	if err != nil {
		return &types.ToolResult{Success: false, Error: err.Error()}, nil
	}
	// SSRF: validate the rendered URL (DNS-pinning + private-range block).
	if err := utils.ValidateURLForSSRF(renderedURL); err != nil {
		return &types.ToolResult{Success: false, Error: fmt.Sprintf("SSRF validation failed: %v", err)}, nil
	}

	var body io.Reader
	if t.cfg.BodyTemplate != "" && t.cfg.Method != "GET" {
		renderedBody, err := renderBodyTemplate(t.cfg.BodyTemplate, params)
		if err != nil {
			return &types.ToolResult{Success: false, Error: err.Error()}, nil
		}
		body = strings.NewReader(renderedBody)
	}

	req, err := http.NewRequestWithContext(ctx, t.cfg.Method, renderedURL, body)
	if err != nil {
		return &types.ToolResult{Success: false, Error: fmt.Sprintf("build request: %v", err)}, nil
	}
	// static headers
	for k, v := range t.cfg.Headers {
		req.Header.Set(k, v)
	}
	// auth
	applyAuth(req, t.cfg.Auth)
	// default content-type for bodies
	if body != nil && req.Header.Get("Content-Type") == "" {
		req.Header.Set("Content-Type", "application/json")
	}

	resp, err := t.client.Do(req)
	if err != nil {
		return &types.ToolResult{Success: false, Error: fmt.Sprintf("http request failed: %v", err)}, nil
	}
	defer resp.Body.Close()

	respBody, err := io.ReadAll(io.LimitReader(resp.Body, maxHTTPToolOutputBytes+1))
	if err != nil {
		return &types.ToolResult{Success: false, Error: fmt.Sprintf("read response: %v", err)}, nil
	}
	bodyStr := string(respBody)
	if len(bodyStr) > maxHTTPToolOutputBytes {
		bodyStr = bodyStr[:maxHTTPToolOutputBytes] + "\n...[truncated]"
	}

	// optional JSONPath-ish extract (single key support: "$.key" or "$.a.b")
	if extract := strings.TrimSpace(t.cfg.ResponseExtract); extract != "" && extract != "$" {
		if extracted, ok := extractJSONPath(bodyStr, extract); ok {
			bodyStr = extracted
		}
	}

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return &types.ToolResult{
			Success: false,
			Error:   fmt.Sprintf("HTTP %d: %s", resp.StatusCode, truncate(bodyStr, 512)),
			Output:  bodyStr,
		}, nil
	}

	return &types.ToolResult{
		Success: true,
		Output:  bodyStr,
	}, nil
}

// renderURLTemplate replaces {var} placeholders with URL-encoded values.
func renderURLTemplate(tmpl string, params map[string]interface{}) (string, error) {
	return renderTemplate(tmpl, params, true)
}

// renderBodyTemplate replaces {var} placeholders with raw JSON values so the
// body stays valid JSON when the template author wrote {"q": {query}}.
func renderBodyTemplate(tmpl string, params map[string]interface{}) (string, error) {
	return renderTemplate(tmpl, params, false)
}

func renderTemplate(tmpl string, params map[string]interface{}, urlEscape bool) (string, error) {
	var b strings.Builder
	i := 0
	for {
		start := strings.Index(tmpl[i:], "{")
		if start < 0 {
			b.WriteString(tmpl[i:])
			break
		}
		b.WriteString(tmpl[i : i+start])
		end := strings.Index(tmpl[i+start:], "}")
		if end < 0 {
			return "", fmt.Errorf("unterminated { in template")
		}
		key := tmpl[i+start+1 : i+start+end]
		val, ok := params[key]
		if !ok {
			return "", fmt.Errorf("missing template parameter: %s", key)
		}
		var s string
		if urlEscape {
			switch v := val.(type) {
			case string:
				s = v
			default:
				jb, _ := json.Marshal(v)
				s = string(jb)
			}
			// utils does not export a query-escape; use net/url via stdlib import
			s = queryEscape(s)
		} else {
			switch v := val.(type) {
			case string:
				// quote strings so {"q": {query}} -> {"q": "value"}
				jb, _ := json.Marshal(v)
				s = string(jb)
			default:
				jb, _ := json.Marshal(v)
				s = string(jb)
			}
		}
		b.WriteString(s)
		i = i + start + end + 1
	}
	return b.String(), nil
}

// queryEscape wraps net/url.QueryEscape.
func queryEscape(s string) string {
	return url.QueryEscape(s)
}

// applyAuth injects credentials from HTTPToolAuth into the request.
func applyAuth(req *http.Request, auth *types.HTTPToolAuth) {
	if auth == nil || auth.AuthType == types.HTTPAuthNone {
		return
	}
	switch auth.AuthType {
	case types.HTTPAuthBearer:
		req.Header.Set("Authorization", "Bearer "+auth.Token)
	case types.HTTPAuthAPIKey:
		h := auth.Header
		if h == "" {
			h = "X-API-Key"
		}
		req.Header.Set(h, auth.Token)
	case types.HTTPAuthBasic:
		// Token is expected to be "user:pass".
		req.Header.Set("Authorization", "Basic "+base64.StdEncoding.EncodeToString([]byte(auth.Token)))
	}
}

// extractJSONPath supports a tiny subset: "$" (whole), "$.key", "$.a.b".
// ponytail: not a full JSONPath impl — covers the common single/double-key
// response shaping case; upgrade path is a real JSONPath lib if users need
// filters/wildcards.
func extractJSONPath(body, path string) (string, bool) {
	path = strings.TrimPrefix(path, "$")
	path = strings.TrimPrefix(path, ".")
	if path == "" {
		return body, true
	}
	var data interface{}
	if err := json.Unmarshal([]byte(body), &data); err != nil {
		return body, false
	}
	for _, key := range strings.Split(path, ".") {
		m, ok := data.(map[string]interface{})
		if !ok {
			return body, false
		}
		data, ok = m[key]
		if !ok {
			return body, false
		}
	}
	out, err := json.Marshal(data)
	if err != nil {
		return body, false
	}
	return string(out), true
}

func truncate(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n] + "..."
}
